/**
 * TypeScript definition for Laravel's DatabaseNotification model
 * Auto-generated by hg:make:typescript
 */

export interface DatabaseNotification {
    readonly id: string;
    readonly type: string;
    readonly notifiableType: string;
    readonly notifiableId: number;
    readonly data: unknown;
    readonly readAt: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
}
