/**
 * TypeScript definition for Laravel Sanctum's PersonalAccessToken model
 * Auto-generated by hg:make:typescript
 */

export interface PersonalAccessToken {
    readonly id: number;
    readonly tokenableType: string;
    readonly tokenableId: number;
    readonly name: string;
    readonly token: string;
    readonly abilities: string[] | null;
    readonly lastUsedAt: string | null;
    readonly expiresAt: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
}
