/**
 * TypeScript definition for the User model
 * Auto-generated by hg:generate:typescript
 */

import type { DatabaseNotification } from '@/types';

export interface User {
    readonly id: number;
    readonly createdAt: string;
    readonly updatedAt: string;
    readonly name: string | null;
    readonly email: string | null;
    readonly password: string;
    readonly personalityType: string | null;
    readonly traitPercentages: Record<string, any>;
    readonly notifications: DatabaseNotification[] | null;
    readonly readNotifications: DatabaseNotification[] | null;
    readonly unreadNotifications: DatabaseNotification[] | null;
}
