/**
 * TypeScript definition for the Visitor model
 * Auto-generated by hg:generate:typescript
 */

import type { PromptRun, User } from '@/types';

export interface Visitor {
    readonly id: string;
    readonly createdAt: string;
    readonly updatedAt: string;
    readonly userId: number | null;
    readonly utmSource: string | null;
    readonly utmMedium: string | null;
    readonly utmCampaign: string | null;
    readonly utmTerm: string | null;
    readonly utmContent: string | null;
    readonly referrer: string | null;
    readonly landingPage: string | null;
    readonly userAgent: string | null;
    readonly ipAddress: string | null;
    readonly firstVisitAt: string;
    readonly lastVisitAt: string;
    readonly visitCount: number;
    readonly convertedAt: string;
    readonly user: User | null;
    readonly promptRuns: PromptRun[] | null;
}
