/**
 * TypeScript definition for the PromptRunResource
 * Auto-generated by hg:make:typescript
 */

import type { N8nResponsePayload } from '@/types/n8n';
import type { UserResource } from '@/types';

export interface PromptRunResource {
    readonly id: number;
    readonly userId: number | null;
    readonly personalityType: string;
    readonly traitPercentages: Array<unknown> | null;
    readonly taskDescription: string;
    readonly selectedFramework: string | null;
    readonly frameworkReasoning: string | null;
    readonly frameworkQuestions: Array<unknown> | null;
    readonly clarifyingAnswers: Array<unknown> | null;
    readonly optimizedPrompt: string | null;
    readonly n8nRequestPayload: Record<string, unknown> | null;
    readonly n8nResponsePayload: N8nResponsePayload | null;
    readonly status: string;
    readonly workflowStage: string;
    readonly errorMessage: string | null;
    readonly completedAt: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
    readonly user?: UserResource | null;
}
