/**
 * TypeScript definition for the PromptRunResource
 * Auto-generated by hg:make:typescript
 */

import type {
    N8nResponsePayload,
    UserResource,
    VisitorResource,
} from '@/types';

/**
 * Trait percentages for personality type
 * Maps trait names to their percentage values (0-100)
 */
export type TraitPercentages = Record<string, number>;

export interface PromptRunResource {
    readonly id: number;
    readonly userId: number | null;
    readonly visitorId: string;
    readonly parentId: number | null;
    readonly personalityType: string | null;
    readonly traitPercentages: TraitPercentages | null;
    readonly taskDescription: string;
    readonly selectedFramework: string | null;
    readonly frameworkReasoning: string | null;
    readonly personalityApproach: string | null;
    readonly frameworkQuestions: string[] | null;
    readonly clarifyingAnswers: (string | null)[] | null;
    readonly optimizedPrompt: string | null;
    readonly n8nRequestPayload: Record<string, unknown> | null;
    readonly n8nResponsePayload: N8nResponsePayload | null;
    readonly status: string;
    readonly workflowStage: string;
    readonly errorMessage: string | null;
    readonly completedAt: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
    readonly visitor?: VisitorResource;
    readonly user?: UserResource | null;
    readonly parent?: PromptRunResource | null;
    readonly children?: readonly PromptRunResource[];
}
