/**
 * TypeScript definition for the UserResource
 * Auto-generated by hg:make:typescript
 */

export interface UserResource {
    readonly id: number;
    readonly name: string;
    readonly email: string;
    readonly createdAt: string;
    readonly updatedAt: string;
    readonly emailVerifiedAt: string | null;
}
