<?php

namespace App\Console\Commands\HiddenGambia\TypeScript\Utils;

/**
 * Class to provide TypeScript definitions for external types not directly in our Models directory.
 */
class ExternalTypeDefinitions
{
    /**
     * Get all external type definitions.
     *
     * @return array An array of type definitions with 'name' and 'definition' keys
     */
    public static function getAll(): array
    {
        return [
            self::getDatabaseNotification(),
            self::getPersonalAccessToken(),
        ];
    }

    /**
     * Get the DatabaseNotification type definition.
     *
     * @return array The type definition
     */
    public static function getDatabaseNotification(): array
    {
        return [
            'name' => 'DatabaseNotification',
            'definition' => "/**
 * TypeScript definition for Laravel's DatabaseNotification model
 * Auto-generated by hg:make:typescript
 */

export interface DatabaseNotification {
    readonly id: string;
    readonly type: string;
    readonly notifiableType: string;
    readonly notifiableId: number;
    readonly data: any;
    readonly readAt: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
}
",
        ];
    }

    /**
     * Get the PersonalAccessToken type definition.
     *
     * @return array The type definition
     */
    public static function getPersonalAccessToken(): array
    {
        return [
            'name' => 'PersonalAccessToken',
            'definition' => "/**
 * TypeScript definition for Laravel Sanctum's PersonalAccessToken model
 * Auto-generated by hg:make:typescript
 */

export interface PersonalAccessToken {
    readonly id: number;
    readonly tokenableType: string;
    readonly tokenableId: number;
    readonly name: string;
    readonly token: string;
    readonly abilities: string[] | null;
    readonly lastUsedAt: string | null;
    readonly expiresAt: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
}
",
        ];
    }
}
