<?php

namespace App\Console\Commands\HiddenGambia\TypeScript\Utils;

use Illuminate\Support\Str;

class ResourceTypeScriptInterfaceExtractor
{
    use PluralHelperTrait;

    /**
     * Extract TypeScript interface from a resource class.
     *
     * @param  string  $resourceClass  Fully qualified class name of the resource
     * @return string TypeScript interface content
     *
     * @throws \Exception If there's an error during extraction
     */
    public function extract(string $resourceClass): string
    {
        try {
            if (! class_exists($resourceClass)) {
                throw new \Exception("Resource class {$resourceClass} does not exist");
            }

            // Get resource name from class name
            $resourceName = class_basename($resourceClass);
            $resourceName = str_replace('Resource', '', $resourceName);

            // Create an instance of the resource
            $reflection = new \ReflectionClass($resourceClass);
            $docComment = $reflection->getDocComment();

            // First, try to extract the entire TypeScript interface directly from the docblock
            if ($docComment && preg_match('/```typescript\s*interface\s+(\w+)\s+\{(.*?)\}\s*```/s', $docComment, $matches)) {
                $interfaceName = $matches[1];
                $interfaceContent = $matches[2];

                // Generate the TypeScript interface file content
                $content = "/**\n";
                $content .= " * TypeScript definition for the {$resourceName}Resource\n";
                $content .= " * Auto-generated by hg:make:typescript\n";
                $content .= " */\n\n";

                // Parse interface content to extract types for imports
                $properties = $this->parsePropertiesFromInterface($interfaceContent);

                // Add imports if needed
                $imports = $this->generateImports($resourceName, $properties);
                if (! empty($imports)) {
                    // Clean up imports to remove built-in TypeScript types
                    $imports = $this->cleanImports($imports);
                    if (! empty($imports)) {
                        $content .= $imports."\n";
                    }
                }

                $content .= "export interface {$interfaceName} {\n";
                $content .= $interfaceContent;
                $content .= "}\n";

                return $content;
            }

            // If direct extraction failed, fall back to the original method
            // Extract properties from the resource
            $properties = $this->extractPropertiesFromResource($resourceClass, $reflection);

            // Generate TypeScript interface
            return $this->generateTypeScriptInterface($resourceName, $properties);
        } catch (\Exception $e) {
            throw new \Exception('Error extracting TypeScript interface: '.$e->getMessage(), 0, $e);
        }
    }

    /**
     * Extract properties from a resource class.
     *
     * @param  string  $resourceClass  Fully qualified class name of the resource
     * @param  \ReflectionClass  $reflection  Reflection of the resource class
     * @return array Properties with their types
     */
    private function extractPropertiesFromResource(string $resourceClass, \ReflectionClass $reflection): array
    {
        $properties = [];

        // Try to extract from docblock first
        $docComment = $reflection->getDocComment();
        if ($docComment) {
            // Extract the model name from the docblock
            $modelName = $this->extractModelNameFromDocblock($docComment);

            // Get the model's fillable attributes if possible
            $modelAttributes = [];
            if ($modelName) {
                $modelAttributes = $this->getModelAttributes($modelName);
            }

            // Try to extract from TypeScript interface in docblock
            // Extract the entire TypeScript interface including the Relationships section
            if (preg_match('/```typescript\s*interface\s+\w+\s+\{(.*?)\}\s*```/s', $docComment, $matches)) {
                $interfaceContent = $matches[1];

                // Extract all properties from the interface
                $properties = $this->parsePropertiesFromInterface($interfaceContent);

                if (! empty($properties)) {
                    // If we have model attributes, validate the properties against them
                    if (! empty($modelAttributes)) {
                        $properties = $this->validatePropertiesAgainstModel($properties, $modelAttributes);
                    }

                    return $properties;
                }
            }
        }

        // If no properties found in docblock, try to analyse the class methods
        $transformMethod = null;

        // Look for transformResource method first
        if ($reflection->hasMethod('transformResource')) {
            $transformMethod = $reflection->getMethod('transformResource');
        }
        // If no transformResource, try toArray
        elseif ($reflection->hasMethod('toArray')) {
            $transformMethod = $reflection->getMethod('toArray');
        }

        if ($transformMethod) {
            $properties = $this->extractPropertiesFromMethod($transformMethod);
        }

        return $properties;
    }

    /**
     * Parse properties from a TypeScript interface string.
     *
     * @param  string  $interfaceContent  The content of the TypeScript interface
     * @return array Extracted properties
     */
    private function parsePropertiesFromInterface(string $interfaceContent): array
    {
        $properties = [];

        // Clean up the interface content
        $cleanedContent = preg_replace('/\/\/.*$/m', '', $interfaceContent); // Remove single-line comments

        // Match property definitions
        // This pattern matches:
        // - optional 'readonly' keyword
        // - property name
        // - optional question mark for optional properties
        // - colon
        // - type definition (which may include complex types like 'readonly Type[]' or 'Type | null')
        // - semicolon
        preg_match_all('/\s*(readonly\s+)?(\w+)(\??):\s+(.*?);/s', $cleanedContent, $matches, PREG_SET_ORDER);

        foreach ($matches as $match) {
            $propertyName = $match[2];
            $isOptional = ! empty($match[3]); // Check if property is optional (has ?)
            $propertyType = trim($match[4]);

            // Store the original property type (not cleaned) so we preserve the full type definition
            $properties[$propertyName] = $propertyType;
        }

        return $properties;
    }

    /**
     * Extract properties from a transform method.
     *
     * @param  \ReflectionMethod  $method  The transform method
     * @return array Properties with their types
     */
    private function extractPropertiesFromMethod(\ReflectionMethod $method): array
    {
        $properties = [];

        // Get the method's source code
        $filename = $method->getFileName();
        $startLine = $method->getStartLine();
        $endLine = $method->getEndLine();

        $source = file($filename);
        $methodSource = implode('', array_slice($source, $startLine - 1, $endLine - $startLine + 1));

        // Extract attribute names and types
        if (preg_match_all('/[\'"](\w+)[\'"](\s*=>\s*.*?)(?:,|\n|$)/s', $methodSource, $attrMatches, PREG_SET_ORDER)) {
            foreach ($attrMatches as $match) {
                $attributeName = $match[1];
                $attributeValue = $match[2];
                $properties[$attributeName] = $this->inferTypeFromAttribute($attributeValue);
            }
        }

        // Check for whenLoaded relationships
        preg_match_all('/[\'"](\w+)[\'"](\s*=>\s*\$this->whenLoaded\s*\([\'"](\w+)[\'"].*?)(?:,|\n|$)/s', $methodSource, $relationMatches, PREG_SET_ORDER);

        foreach ($relationMatches as $match) {
            $attributeName = $match[1];
            $relationName = $match[3] ?? $attributeName;
            $relationContent = $match[2];

            // Always mark relationships as nullable for defensive programming
            if (strpos($relationContent, 'Resource::collection') !== false || strpos($relationContent, '[]') !== false) {
                // Collection relationship
                if (preg_match('/(\w+)Resource::collection/', $relationContent, $resourceMatches)) {
                    $relatedModel = $resourceMatches[1];
                    $properties[$attributeName] = "{$relatedModel}[] | null";
                } else {
                    // Try to infer the model name from the relationship name
                    $relatedModel = Str::singular(Str::studly($relationName));
                    $properties[$attributeName] = "{$relatedModel}[] | null";
                }
            } elseif (strpos($relationContent, 'new') !== false && strpos($relationContent, 'Resource') !== false) {
                // Single resource relationship
                if (preg_match('/new\s+(\w+)Resource/', $relationContent, $resourceMatches)) {
                    $relatedModel = $resourceMatches[1];
                    $properties[$attributeName] = "{$relatedModel} | null";
                } else {
                    // Try to infer the model name from the relationship name
                    $relatedModel = Str::studly($relationName);
                    $properties[$attributeName] = "{$relatedModel} | null";
                }
            } else {
                // Try to infer the model name from the relationship name
                if (Str::endsWith($relationName, 's')) {
                    // Likely a HasMany or BelongsToMany relationship
                    $relatedModel = Str::singular(Str::studly($relationName));
                    $properties[$attributeName] = "{$relatedModel}[] | null";
                } else {
                    // Likely a HasOne or BelongsTo relationship
                    $relatedModel = Str::studly($relationName);
                    $properties[$attributeName] = "{$relatedModel} | null";
                }
            }
        }

        return $properties;
    }

    /**
     * Infer TypeScript type from PHP attribute.
     *
     * @param  string  $attributeValue  PHP attribute value
     * @return string TypeScript type
     */
    private function inferTypeFromAttribute(string $attributeValue): string
    {
        if (strpos($attributeValue, 'integer') !== false || strpos($attributeValue, '->id') !== false) {
            return 'number';
        }

        if (strpos($attributeValue, 'boolean') !== false || strpos($attributeValue, '? true : false') !== false) {
            return 'boolean';
        }

        if (strpos($attributeValue, '->format') !== false || strpos($attributeValue, 'date') !== false) {
            return 'string';
        }

        if (strpos($attributeValue, 'Resource::collection') !== false) {
            // Extract the resource type from collection
            if (preg_match('/(\w+)Resource::collection/', $attributeValue, $matches)) {
                return "{$matches[1]}Resource[] | null";
            }

            return 'any[] | null';
        }

        if (strpos($attributeValue, 'new') !== false && strpos($attributeValue, 'Resource') !== false) {
            // Extract the resource type
            if (preg_match('/new\s+(\w+)Resource/', $attributeValue, $matches)) {
                return "{$matches[1]}Resource | null";
            }

            return 'any | null';
        }

        // Default to string | null
        return 'string | null';
    }

    /**
     * Map PHP type to TypeScript type.
     */
    private function mapPhpTypeToTypeScript(string $phpType): string
    {
        $typeMap = [
            'int' => 'number',
            'integer' => 'number',
            'float' => 'number',
            'double' => 'number',
            'string' => 'string',
            'bool' => 'boolean',
            'boolean' => 'boolean',
            'array' => 'any[]',
            'object' => 'Record<string, any>',
            'mixed' => 'any',
            'Carbon\\Carbon' => 'string',
            'Illuminate\\Support\\Carbon' => 'string',
            'DateTime' => 'string',
            'Illuminate\\Support\\Collection' => 'any[]',
        ];

        // Handle nullable types (e.g., ?string)
        if (Str::startsWith($phpType, '?')) {
            $baseType = Str::substr($phpType, 1);

            return ($typeMap[$baseType] ?? 'any').' | null';
        }

        // Handle array types (e.g., string[])
        if (Str::contains($phpType, '[]')) {
            $baseType = Str::replace('[]', '', $phpType);

            return ($typeMap[$baseType] ?? 'any').'[]';
        }

        return $typeMap[$phpType] ?? 'any';
    }

    /**
     * Extract the model name from the resource docblock.
     *
     * @param  string  $docComment  The resource docblock
     * @return string|null The model name or null if not found
     */
    private function extractModelNameFromDocblock(string $docComment): ?string
    {
        // Look for @see \App\Models\ModelName pattern
        if (preg_match('/@see\s+\\\\App\\\\Models\\\\(\w+)/', $docComment, $matches)) {
            return $matches[1];
        }

        // Look for TypeScript interface pattern
        if (preg_match('/```typescript\s*interface\s+(\w+)\s+\{/', $docComment, $matches)) {
            return $matches[1];
        }

        return null;
    }

    /**
     * Get the model's fillable attributes and relationships.
     *
     * @param  string  $modelName  The model name
     * @return array The model's attributes and relationships
     */
    private function getModelAttributes(string $modelName): array
    {
        $modelClass = "\\App\\Models\\{$modelName}";
        if (! class_exists($modelClass)) {
            return ['attributes' => [], 'relationships' => []];
        }

        $model = new $modelClass;
        $tableName = $model->getTable();

        // Get column information from migrations
        $migrationAnalyser = app(\App\Console\Commands\Shared\MigrationAnalyser::class);
        $columns = $migrationAnalyser->getTableColumns($tableName);

        // Create a column map for easy lookup
        $columnMap = [];
        if (is_array($columns)) {
            foreach ($columns as $column) {
                if (is_array($column) && isset($column['name'])) {
                    $columnMap[$column['name']] = $column;
                }
            }
        }

        $attributes = [];
        $fillable = $model->getFillable();

        foreach ($fillable as $attribute) {
            $attributes[$attribute] = [
                'name' => $attribute,
                'nullable' => isset($columnMap[$attribute]) ? $columnMap[$attribute]['nullable'] : false,
            ];
        }

        // Add timestamps if the model uses them
        if ($model->usesTimestamps()) {
            $createdAtColumn = $model->getCreatedAtColumn();
            $updatedAtColumn = $model->getUpdatedAtColumn();

            $attributes[$createdAtColumn] = [
                'name' => $createdAtColumn,
                'nullable' => false,
            ];

            $attributes[$updatedAtColumn] = [
                'name' => $updatedAtColumn,
                'nullable' => false,
            ];
        }

        // Get primary key
        $primaryKey = $model->getKeyName();
        $attributes[$primaryKey] = [
            'name' => $primaryKey,
            'nullable' => false,
        ];

        // Get relationships
        $relationships = [];
        $reflection = new \ReflectionClass($modelClass);
        $methods = $reflection->getMethods(\ReflectionMethod::IS_PUBLIC);

        foreach ($methods as $method) {
            // Skip methods that are not potential relationships
            if ($method->getNumberOfParameters() > 0 || $method->isStatic() || $method->isAbstract()) {
                continue;
            }

            // Get method source to check if it's a relationship
            $filename = $method->getFileName();
            $startLine = $method->getStartLine();
            $endLine = $method->getEndLine();

            if (! $filename || ! file_exists($filename)) {
                continue;
            }

            $source = file($filename);
            $methodSource = implode('', array_slice($source, $startLine - 1, $endLine - $startLine + 1));

            // Check if method is a relationship
            if (preg_match('/return\s+\$this->(hasOne|hasMany|belongsTo|belongsToMany|morphTo|morphMany|morphToMany|morphedByMany)\(/', $methodSource)) {
                $relationships[$method->getName()] = [
                    'name' => $method->getName(),
                    'type' => 'relationship',
                ];
            }
        }

        return [
            'attributes' => $attributes,
            'relationships' => $relationships,
        ];
    }

    /**
     * Validate properties against the model's attributes and relationships.
     *
     * @param  array  $properties  The extracted properties
     * @param  array  $modelAttributes  The model's attributes and relationships
     * @return array The validated properties
     */
    private function validatePropertiesAgainstModel(array $properties, array $modelAttributes): array
    {
        $validatedProperties = [];

        foreach ($properties as $name => $type) {
            $snakeName = $this->camelToSnake($name);

            // Check if this property exists in the model attributes
            if (isset($modelAttributes['attributes'][$snakeName])) {
                $attribute = $modelAttributes['attributes'][$snakeName];

                // Update the type if the attribute is nullable
                if (isset($attribute['nullable']) && $attribute['nullable'] && ! str_contains($type, '| null')) {
                    $type = $type.' | null';
                }

                $validatedProperties[$name] = $type;
            }
            // Check if this is a relationship
            elseif (isset($modelAttributes['relationships'][$snakeName])) {
                $validatedProperties[$name] = $type;
            }
            // Otherwise, keep the property as is
            else {
                $validatedProperties[$name] = $type;
            }
        }

        return $validatedProperties;
    }

    /**
     * Convert snake_case to camelCase.
     */
    private function snakeToCamel(string $input): string
    {
        return Str::camel($input);
    }

    /**
     * Convert camelCase to snake_case.
     */
    private function camelToSnake(string $input): string
    {
        return Str::snake($input);
    }

    /**
     * Generate TypeScript interface for a resource.
     */
    public function generate(string $resourceName): void
    {
        $resourceClass = "App\\Http\\Resources\\{$resourceName}";

        if (! class_exists($resourceClass)) {
            echo "Resource class {$resourceClass} does not exist.\n";

            return;
        }

        $properties = $this->extractResourceProperties($resourceClass);
        $content = $this->generateTypeScriptInterface($resourceName, $properties);

        $outputPath = resource_path("js/types/resources/{$resourceName}.ts");
        $this->ensureDirectoryExists(dirname($outputPath));
        file_put_contents($outputPath, $content);

        // Generate composables in a separate file
        $composablesContent = $this->generateComposablesFile($resourceName);
        $composablesDir = resource_path('js/composables/resources');
        $this->ensureDirectoryExists($composablesDir);

        $resourceNameBase = preg_replace('/Resource$/', '', $resourceName);
        $composablesPath = "{$composablesDir}/use{$resourceNameBase}.ts";
        file_put_contents($composablesPath, $composablesContent);

        echo "Generated: /resources/js/types/resources/{$resourceName}.ts\n";
        echo "Generated: /resources/js/composables/resources/use{$resourceNameBase}.ts\n";
    }

    /**
     * Generate TypeScript interface content.
     */
    private function generateTypeScriptInterface(string $resourceName, array $properties): string
    {
        $resourceNameBase = preg_replace('/Resource$/', '', $resourceName);

        // Process properties to ensure consistent type naming
        $processedProperties = $this->processPropertyTypes($properties);

        // Start building the TypeScript file
        $content = "/**\n";
        $content .= " * TypeScript definition for the {$resourceName}\n";
        $content .= " * Auto-generated by hg:generate:typescript\n";
        $content .= " */\n\n";

        // Add imports from the generateImports method
        $content .= $this->generateImports($resourceNameBase, $processedProperties);

        // Add interface definition
        $content .= "export interface {$resourceNameBase} {\n";

        // Separate regular properties and relationship properties
        $regularProperties = [];
        $relationshipProperties = [];

        foreach ($processedProperties as $attribute => $type) {
            // Check if this is a relationship property
            if ($this->isResourceType($type) ||
                preg_match('/^([A-Z][a-zA-Z0-9_]*)Resource(\[\])?\s*\|\s*null$/', $type)) {
                $relationshipProperties[$attribute] = $type;
            } else {
                $regularProperties[$attribute] = $type;
            }
        }

        // Add regular attributes first
        foreach ($regularProperties as $attribute => $type) {
            // Convert snake_case to camelCase for property names
            $camelCaseAttribute = Str::camel($attribute);
            $content .= "    readonly {$camelCaseAttribute}: {$type};\n";
        }

        // Add a separator comment if we have relationship properties
        if (! empty($relationshipProperties)) {
            $content .= "\n    // Relationships\n";
        }

        // Add relationship properties
        foreach ($relationshipProperties as $attribute => $type) {
            // Convert snake_case to camelCase for property names
            $camelCaseAttribute = Str::camel($attribute);

            // Relationship properties are optional (use ? syntax)
            $content .= "    readonly {$camelCaseAttribute}?: {$type};\n";
        }

        $content .= "}\n";

        return $content;
    }

    /**
     * Process property types to ensure consistent naming.
     */
    private function processPropertyTypes(array $properties): array
    {
        $processedProperties = [];
        foreach ($properties as $attribute => $type) {
            // Ensure relationship properties are properly typed with Resource suffix
            if (preg_match('/^([A-Z][a-zA-Z0-9_]*)(\[\])?\s*\|\s*null$/', $type, $matches)) {
                $baseType = $matches[1];
                $isArray = ! empty($matches[2]);

                // Check if we need to add Resource suffix
                if (! Str::endsWith($baseType, 'Resource')) {
                    // For relationship types, ensure they have the correct Resource suffix
                    $type = $isArray ? "{$baseType}Resource[] | null" : "{$baseType}Resource | null";
                }
            }

            $processedProperties[$attribute] = $type;
        }

        return $processedProperties;
    }

    /**
     * Generate composables file for a resource.
     */
    private function generateComposablesFile(string $resourceName): string
    {
        $resourceNameBase = preg_replace('/Resource$/', '', $resourceName);
        $apiEndpoint = $this->getApiEndpoint($resourceNameBase);
        $pluralFunctionName = $this->getPluralFunctionName($resourceNameBase);
        $pluralVariableName = $this->getPluralVariableName($resourceNameBase);

        // Start building the TypeScript file
        $content = "/**\n";
        $content .= " * TypeScript composable for the {$resourceName}\n";
        $content .= " * Auto-generated by hg:generate:typescript\n";
        $content .= " */\n\n";

        // Add imports
        $content .= "import { ref } from 'vue';\n";
        $content .= "import type { Ref } from 'vue';\n";
        $content .= "import axios from 'axios';\n";
        $content .= "import type { {$resourceNameBase} } from '@/types';\n";
        $content .= "import type { Paginated } from '@/types/shared/pagination';\n\n";

        // useGet{Resource} composable
        $content .= "export function useGet{$resourceNameBase}(id: number) {\n";
        $content .= '    const '.Str::camel($resourceNameBase).": Ref<{$resourceNameBase} | null> = ref(null);\n";
        $content .= "    const loading: Ref<boolean> = ref(false);\n";
        $content .= "    const error: Ref<string | null> = ref(null);\n\n";
        $content .= "    const fetch = async () => {\n";
        $content .= "        loading.value = true;\n";
        $content .= "        error.value = null;\n";
        $content .= "        try {\n";
        $content .= "            const response = await axios.get(`/api/{$apiEndpoint}/\${id}`);\n";
        $content .= '            '.Str::camel($resourceNameBase).".value = response.data.data;\n";
        $content .= "        }\n";
        $content .= "        catch (e) {\n";
        $content .= "            error.value = e instanceof Error ? e.message : 'An error occurred';\n";
        $content .= "        }\n";
        $content .= "        finally {\n";
        $content .= "            loading.value = false;\n";
        $content .= "        }\n";
        $content .= "    };\n\n";
        $content .= "    return {\n";
        $content .= '        '.Str::camel($resourceNameBase).",\n";
        $content .= "        loading,\n";
        $content .= "        error,\n";
        $content .= "        fetch,\n";
        $content .= "    };\n";
        $content .= "}\n\n";

        // useList{Resources} composable
        $content .= "export function useList{$pluralFunctionName}() {\n";
        $content .= "    const {$pluralVariableName}: Ref<{$resourceNameBase}[]> = ref([]);\n";
        $content .= "    const pagination: Ref<Paginated<{$resourceNameBase}>['meta'] | null> = ref(null);\n";
        $content .= "    const loading: Ref<boolean> = ref(false);\n";
        $content .= "    const error: Ref<string | null> = ref(null);\n\n";
        $content .= "    const fetch = async (page = 1, perPage = 15) => {\n";
        $content .= "        loading.value = true;\n";
        $content .= "        error.value = null;\n";
        $content .= "        try {\n";
        $content .= "            const response = await axios.get<Paginated<{$resourceNameBase}>>(`/api/{$apiEndpoint}?page=\${page}&per_page=\${perPage}`);\n";
        $content .= "            {$pluralVariableName}.value = response.data.data;\n";
        $content .= "            pagination.value = response.data.meta;\n";
        $content .= "        }\n";
        $content .= "        catch (e) {\n";
        $content .= "            error.value = e instanceof Error ? e.message : 'An error occurred';\n";
        $content .= "        }\n";
        $content .= "        finally {\n";
        $content .= "            loading.value = false;\n";
        $content .= "        }\n";
        $content .= "    };\n\n";
        $content .= "    return {\n";
        $content .= "        {$pluralVariableName},\n";
        $content .= "        pagination,\n";
        $content .= "        loading,\n";
        $content .= "        error,\n";
        $content .= "        fetch,\n";
        $content .= "    };\n";
        $content .= "}\n";

        return $content;
    }

    /**
     * Check if a type is a resource type.
     */
    private function isResourceType(string $type): bool
    {
        // Handle array types (e.g., UserResource[] or readonly UserResource[])
        if (Str::contains($type, '[]')) {
            $baseType = Str::before($type, '[]');
            // Remove "readonly" if present
            $baseType = Str::contains($baseType, 'readonly') ? Str::after(Str::trim($baseType), 'readonly ') : $baseType;

            return $this->isResourceType($baseType);
        }

        // Handle nullable types (e.g., UserResource | null)
        if (Str::contains($type, ' | null')) {
            $baseType = Str::before($type, ' | null');

            return $this->isResourceType($baseType);
        }

        // Check if the type is likely a resource (has uppercase first letter and "Resource" suffix)
        // or is a model type (has uppercase first letter but no "Resource" suffix)
        return preg_match('/^[A-Z][a-zA-Z0-9_]*Resource$/', $type) ||
               preg_match('/^[A-Z][a-zA-Z0-9_]*$/', $type);
    }

    /**
     * Ensure a directory exists.
     */
    private function ensureDirectoryExists(string $path): void
    {
        if (! is_dir($path)) {
            mkdir($path, 0777, true);
        }
    }

    /**
     * Generate imports for the resource.
     *
     * @param  array<string, string>  $properties
     */
    private function generateImports(string $resourceName, array $properties): string
    {
        $imports = [];
        $localImports = [];

        foreach ($properties as $attribute => $type) {
            // Only extract types that end with "Resource" - these are our custom types
            // This approach is much simpler and more reliable than trying to filter out built-ins
            preg_match_all('/\b([A-Z][a-zA-Z0-9]*Resource)\b/', $type, $resourceMatches);

            if (! empty($resourceMatches[1])) {
                foreach ($resourceMatches[1] as $resourceType) {
                    $resourceType = trim($resourceType);

                    // Skip if empty after trim
                    if (empty($resourceType)) {
                        continue;
                    }

                    // Skip the current resource
                    if ($resourceType === $resourceName || $resourceType === $resourceName.'Resource') {
                        continue;
                    }

                    // Special case for Room - use relative import
                    if ($resourceType === 'RoomResource') {
                        if (! in_array($resourceType, $localImports)) {
                            $localImports[] = $resourceType;
                        }
                    } else {
                        // Add to global imports if not already there
                        if (! in_array($resourceType, $imports)) {
                            $imports[] = $resourceType;
                        }
                    }
                }
            }
        }

        // Sort imports alphabetically
        sort($imports);
        sort($localImports);

        $content = '';

        // Add grouped imports from @/types
        if (! empty($imports)) {
            $content .= 'import type { '.implode(', ', $imports)." } from '@/types';\n";
        }

        // Add local imports
        foreach ($localImports as $import) {
            $content .= "import type { {$import} } from './{$import}';\n";
        }

        if (! empty($imports) || ! empty($localImports)) {
            $content .= "\n";
        }

        return $content;
    }

    /**
     * Clean up imports to remove built-in TypeScript types.
     */
    private function cleanImports(string $imports): string
    {
        // List of built-in TypeScript types that should not be imported
        $builtInTypes = ['Record', 'Array', 'Map', 'Set', 'Promise', 'Partial', 'Required', 'Pick', 'Omit', 'Readonly', 'String', 'Number', 'Boolean', 'Object', 'Function', 'Date', 'Unknown'];

        // Parse and clean the import statement
        if (preg_match('/import type \{\s*([^}]+)\s*\} from (.+);/', $imports, $matches)) {
            $importList = $matches[1];
            $fromClause = $matches[2];

            // Split by comma and filter out built-in types
            $types = array_map('trim', explode(',', $importList));
            $cleanTypes = array_filter($types, function ($type) use ($builtInTypes) {
                return ! in_array(trim($type), $builtInTypes);
            });

            // If we have remaining types, rebuild the import statement
            if (! empty($cleanTypes)) {
                return 'import type { '.implode(', ', $cleanTypes).' } from '.$fromClause.';';
            } else {
                return ''; // No imports needed
            }
        }

        return $imports; // Return as-is if we can't parse it
    }
}
